name: reusable-build-and-push-containers

on:
  workflow_call:
    inputs:
      container_name:
        description: "Name of the variant container (e.g., code, rdesktop)"
        required: true
        type: string

jobs:
  shared-config:
    name: Shared Configuration
    runs-on: ubuntu-latest
    outputs:
      container_name: ${{ inputs.container_name }}
      base_image: ${{ steps.config.outputs.base_image }}
      base_version: ${{ steps.config.outputs.base_version }}
      bootc_image: ${{ steps.config.outputs.bootc_image }}
      release_tag: ${{ steps.release.outputs.tag }}
      user: ${{ steps.userinfo.outputs.user_username }}
      user_password: ${{ steps.userinfo.outputs.user_password }}
    steps:
      - name: Fetch user configuration and use output
        id: userinfo
        uses: gbraad-actions/shared-config@v2
        with:
          config_repo: https://github.com/${{ vars.OWNER }}/shared-config.git
          config_file: user.ini
          use_output: true
      - name: Fetch container configuration and use output
        id: config
        uses: gbraad-actions/shared-config@v2
        with:
          config_repo: https://github.com/${{ github.repository_owner }}/shared-config.git
          config_file: containers/${{ github.repository }}/${{ inputs.container_name }}.ini
          use_output: true
      - name: Set release tag
        id: release
        run: |
          echo "tag=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

  build-arm64:
    needs: shared-config
    name: Build ARM64
    uses: ./.github/workflows/reusable-build-bootable-container.yml
    with:
      container_name: ${{ needs.shared-config.outputs.container_name }}
      bootc_image: ${{ needs.shared-config.outputs.bootc_image }}
      base_version: ${{ needs.shared-config.outputs.base_version }}
      arch: "arm64"
    secrets: inherit

  build-amd64:
    needs: shared-config
    name: Build AMD64
    uses: ./.github/workflows/reusable-build-bootable-container.yml
    with:
      container_name: ${{ needs.shared-config.outputs.container_name }}
      bootc_image: ${{ needs.shared-config.outputs.bootc_image }}
      base_version: ${{ needs.shared-config.outputs.base_version }}
      arch: "amd64"
    secrets: inherit

  push-manifest:
    needs:
      - shared-config
      - build-arm64
      - build-amd64
    name: Push
    uses: ./.github/workflows/reusable-push-bootable-manifest.yml
    with:
      container_name: ${{ needs.shared-config.outputs.container_name }}
      base_version: ${{ needs.shared-config.outputs.base_version }}
      release_tag: ${{ needs.shared-config.outputs.release_tag }}
    secrets: inherit
